_target_: src.models.distillModule.DistillModule

teacher_ckpt: null
apply_recon: True

student:
  _target_: src.models.components.efficientNet.EncoderEfficientNet
  version: 'efficientnet-b0'
  frozen: False
  in_channels: 1
  in_features: 1280
  out_features: 128
  num_outputs: 2

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.0001
