_target_: src.models.efficientNetModule.EfficientNetModule

classifier:
  _target_: src.models.components.multitask_mlp.MultiTaskMLP
  shared_layer: True
  input_dim: 128
  hidden_dim: 256
  num_classes: 6

state_dict: Null
version: 'efficientnet-b0'
in_channels: 1
num_classes: 128
frozen: False


optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.0001

scheduler: Null
