_target_: src.models.mlp_module.MultiTaskMLPModule

classifier:
  _target_: src.models.components.multitask_mlp.MultiTaskMLP
  shared_layer: True
  input_dim: 128
  hidden_dim: 256 
  num_classes: 6

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.0001
  # weight_decay: 0.0

scheduler: Null

embedder: 'VGGish'

embedder_ckpt: Null
