defaults:
  - model_checkpoint.yaml
  - early_stopping.yaml
  - model_summary.yaml
  - rich_progress_bar.yaml
  - umap_latent.yaml
  - reconstructor.yaml
  - _self_

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "epoch_{epoch:03d}"
  monitor: "val/loss"
  mode: "min"
  save_last: True
  auto_insert_metric_name: False
  every_n_epochs: 1 # number of epochs between checkpoints
  save_top_k: 3 # save k best models (determined by above metric)

early_stopping:
  monitor: "val/loss"
  patience: 10
  mode: "min"

model_summary:
  max_depth: -1
